### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by sjzier** [geifmany/cifar-vgg#10]
Using TensorFlow backend.
(10, 4)
WARNING:tensorflow:From /Users/mengfan/PycharmProjects/untitled1/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "/Users/mengfan/PycharmProjects/untitled1/VGG2.py", line 370, in <module>
    main()
  File "/Users/mengfan/PycharmProjects/untitled1/VGG2.py", line 312, in main
    model = VGG()
  File "/Users/mengfan/PycharmProjects/untitled1/VGG2.py", line 120, in __init__
    self.model = self.train(self.model)
  File "/Users/mengfan/PycharmProjects/untitled1/VGG2.py", line 291, in train
    validation_data=(X_test, y_test),callbacks=[reduce_lr],verbose=2)
  File "/Users/mengfan/PycharmProjects/untitled1/venv/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/mengfan/PycharmProjects/untitled1/venv/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/Users/mengfan/PycharmProjects/untitled1/venv/lib/python3.6/site-packages/keras/engine/training_generator.py", line 40, in fit_generator
    model._make_train_function()
  File "/Users/mengfan/PycharmProjects/untitled1/venv/lib/python3.6/site-packages/keras/engine/training.py", line 496, in _make_train_function
    raise RuntimeError('You must compile your model before using it.')
RuntimeError: You must compile your model before using it.

Process finished with exit code 1

出现这个问题如何解决

**Comment by ludwikbukowski** [comment]
As it says, compile it before using.
That should work:
```
learning_rate = 0.1
lr_decay = 1e-6
sgd = optimizers.SGD(lr=learning_rate, decay=lr_decay, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
                 optimizer=sgd,
                 metrics=['accuracy'])
```

then, for instance, you can try to evaluate it:
```
import numpy as np

def vgg_normalize(X_train, X_test):
    mean = np.mean(X_train, axis=(0, 1, 2, 3))
    std = np.std(X_train, axis=(0, 1, 2, 3))
    X_train = (X_train - mean) / (std + 1e-7)
    X_test = (X_test - mean) / (std + 1e-7)
    return X_train, X_test

(x_train, y_train), (x_test, y_test) = cifar10.load_data()
x_train, x_test = vgg_normalize(x_train, x_test )
y_test = to_categorical(y_test, 10)
scores = m.evaluate(x_test, y_test, verbose=1)
print('Test loss:', scores[0])
print('Test accuracy:', scores[1])

```
